name: Build APK - Beta

env:
  # The name of the main module repository
  main_project_module: udyneos

  # The name of the Play Store
  playstore_name: zashapp

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Set Current Date As Env Variable
      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      # Set Repository Name As Env Variable
      - name: Set repository name as env variable
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - name: Set Up JDK
        run: |
            sudo apt update && sudo apt install openjdk-17-jdk
            echo "export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" > ~/.bashrc
           echo "export PATH=$JAVA_HOME/bin:$PATH" > ~/.bashrc
           source ~/.bashrc
           java --version
           

      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      
      - name: Install SDK
        run: |
           rm -rf ~/Android/Sdk
           mkdir -p ~/Android/Sdk/cmdline-tools/latest
           cd ~/Android/Sdk
           wget -q https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -O tools.zip
           unzip -q tools.zip -d cmdline-tools/latest
           mv cmdline-tools/latest/cmdline-tools/* cmdline-tools/latest/
           rmdir cmdline-tools/latest/cmdline-tools
           rm tools.zip
           yes | ~/Android/Sdk/cmdline-tools/latest/bin/sdkmanager --licenses
           ~/Android/Sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"
           ls ~/Android/Sdk/platforms/
           ls ~/Android/Sdk/build-tools/
           echo "sdk.dir=/home/$(whoami)/Android/Sdk" > local.properties

      # Run Build Project
      - name: Build gradle project + debug
        run: |
           ./gradlew clean
           ./gradlew build

      # Create APK Release
      - name: Build apk release project (APK) - ${{ env.main_project_module }} module
        run: |
           ./gradlew :app:assembleRelease

      # Upload Artifact Build

      # Noted For Output [main_project_module]/build/outputs/apk/release/
      - name: Upload APK Release - ${{ env.repository_name }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.date_today }} - ${{ env.playstore_name }} - ${{ env.repository_name }} - APK(s) release generated
          path: ${{ env.main_project_module }}/build/outputs/apk/release/
